--------------------------------------- MEMBER 테이블 

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	NVARCHAR2(10)		NOT NULL,
	"MEMBER_PW"	NVARCHAR2(30)		NOT NULL,
	"MEMBER_EMAIL"	NVARCHAR2(50)		NOT NULL,
	"MEMBER_NICKNAME"	NVARCHAR2(20)		NOT NULL,
	"MEMBER_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_TEL"	NVARCHAR2(13)		NOT NULL,
	"MEMBER_HOME_TEL"	NVARCHAR2(13)		NULL,
	"MEMBER_ADRESS"	NVARCHAR2(300)		NULL,
	"PROFILE_IMG"	NVARCHAR2(1000)		NULL,
	"PERSONAL_CODE"	CHAR(13)		NOT NULL,
	"BACKGROUND_COLOR"	NVARCHAR2(20)	DEFAULT 'CDE3EE'	NOT NULL,
	"AUTHORITY"	NUMBER	DEFAULT 1	NOT NULL
	"INTRODUCTION" NVARCHAR2(2000) NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호(PK)';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원ID';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원 닉네임';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '회원 탈퇴여부(Y / N)';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '회원 전화번호(휴대전화)';

COMMENT ON COLUMN "MEMBER"."MEMBER_HOME_TEL" IS '회원 전화번호(집)';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADRESS" IS '회원 주소(우편번소, 도로명/지번, 상세주소)';

COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '프로필 이미지 경로';

COMMENT ON COLUMN "MEMBER"."PERSONAL_CODE" IS '주민등록번호';

COMMENT ON COLUMN "MEMBER"."BACKGROUND_COLOR" IS '홈페이지 배경색';

COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '회원권한(1:일반 이용자, 2 : 관리자)';

COMMENT ON COLUMN "MEMBER"."INTRODUCTION" IS '자기소개';


-- 제약조건
ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "MEMBER_DEL_CHECK"
CHECK("MEMBER_DEL_FL" IN ('Y', 'N'));



SELECT MEMBER_NO, MEMBER_ID, MEMBER_PW, MEMBER_EMAIL, MEMBER_NICKNAME,
MEMBER_TEL, MEMBER_HOME_TEL, MEMBER_ADRESS, PROFILE_IMG, BACKGROUND_COLOR, AUTHORITY, INTRODUCTION
FROM "MEMBER"
WHERE MEMBER_ID = 'test123'
AND MEMBER_DEL_FL = 'N';

SELECT * FROM "MEMBER";


------------------------------------ 게시판 종류 "BOARD_TYPE" 테이블
CREATE TABLE "BOARD_TYPE" (
	"BOARD_TYPE_NO"	NUMBER		NOT NULL,
	"BOARD_TYPE_NAME"	NVARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_TYPE_NO" IS '게시판 종류 번호(PK)';

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_TYPE_NAME" IS '게시판 종류 이름';


ALTER TABLE "BOARD_TYPE" ADD CONSTRAINT "PK_BOARD_TYPE" PRIMARY KEY (
	"BOARD_TYPE_NO"
);



------------------------------------ 게시판 BOARD 테이블 쿼리
CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	NVARCHAR2(30)		NOT NULL,
	"BOARD_CONTENT"	NVARCHAR2(2000)		NOT NULL,
	"BOARD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_UPDATE_DATE"	DATE	DEFAULT SYSDATE NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_TYPE_NO"	NUMBER	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호(PK)';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 상세내용';

COMMENT ON COLUMN "BOARD"."BOARD_DATE" IS '게시글 작성일';

COMMENT ON COLUMN "BOARD"."BOARD_UPDATE_DATE" IS '게시글 수정일';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '작성회원(FK)';

COMMENT ON COLUMN "BOARD"."BOARD_TYPE_NO" IS '게시판 종류 번호(FK)';


-- PK 제약조건
ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);


ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
) ON DELETE CASCADE;



ALTER TABLE "BOARD" ADD CONSTRAINT "FK_BOARD_TYPE_TO_BOARD_1" FOREIGN KEY (
	"BOARD_TYPE_NO"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_TYPE_NO"
) ON DELETE CASCADE;


------------------------------------ 사진첩 "PHOTO" 테이블
CREATE TABLE "PHOTO" (
	"PHOTO_NO"	NUMBER		NOT NULL,
	"PHOTO_TITLE"	NVARCHAR2(30)		NOT NULL,
	"PHOTO_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PHOTO_UPDATE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_TYPE_NO"	NUMBER	DEFAULT 2	NOT NULL
);

COMMENT ON COLUMN "PHOTO"."PHOTO_NO" IS '사진첩 번호(PK)';

COMMENT ON COLUMN "PHOTO"."PHOTO_TITLE" IS '사진첩 제목';

COMMENT ON COLUMN "PHOTO"."PHOTO_DATE" IS '사진첩 작성일';

COMMENT ON COLUMN "PHOTO"."PHOTO_UPDATE_DATE" IS '사진첩 수정일';

COMMENT ON COLUMN "PHOTO"."MEMBER_NO" IS '작성회원(FK)';

COMMENT ON COLUMN "PHOTO"."BOARD_TYPE_NO" IS '게시판 종류 번호(FK)';


-- PK 제약 조건
ALTER TABLE "PHOTO" ADD CONSTRAINT "PK_PHOTO" PRIMARY KEY (
	"PHOTO_NO"
);

ALTER TABLE "PHOTO" ADD CONSTRAINT "FK_MEMBER_TO_PHOTO_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
) ON DELETE CASCADE;



ALTER TABLE "PHOTO" ADD CONSTRAINT "FK_BOARD_TYPE_TO_PHOTO_1" FOREIGN KEY (
	"BOARD_TYPE_NO"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_TYPE_NO"
) ON DELETE CASCADE;


------------------------------------ 방명록 "VISITOR" 테이블
CREATE TABLE "VISITOR" (
	"VISITOR_NO"	NUMBER		NOT NULL,
	"VISITOR_CONTENT"	NVARCHAR2(2000)		NOT NULL,
	"VISITOR_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"VISITOR_UPDATE_DATE"	DEFAULT SYSDATE DATE		NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_TYPE_NO"	NUMBER	DEFAULT 3	NOT NULL
);

COMMENT ON COLUMN "VISITOR"."VISITOR_NO" IS '방명록 번호(PK)';

COMMENT ON COLUMN "VISITOR"."VISITOR_CONTENT" IS '방명록 내용';

COMMENT ON COLUMN "VISITOR"."VISITOR_DATE" IS '방먕록 작성일';

COMMENT ON COLUMN "VISITOR"."VISITOR_UPDATE_DATE" IS '방명록 수정일';

COMMENT ON COLUMN "VISITOR"."MEMBER_NO" IS '작성회원(FK)';

COMMENT ON COLUMN "VISITOR"."BOARD_TYPE_NO" IS '게시판 종류 번호(FK)';


-- 방명록
ALTER TABLE "VISITOR" ADD CONSTRAINT "PK_VISITOR" PRIMARY KEY (
	"VISITOR_NO"
);

ALTER TABLE "VISITOR" ADD CONSTRAINT "FK_MEMBER_TO_VISITOR_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
) ON DELETE CASCADE;

ALTER TABLE "VISITOR" ADD CONSTRAINT "FK_BOARD_TYPE_TO_VISITOR_1" FOREIGN KEY (
	"BOARD_TYPE_NO"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_TYPE_NO"
) ON DELETE CASCADE;


------------------------------------ 메모장 "NOTE" 테이블
CREATE TABLE "NOTE" (
	"NOTE_NO"	NUMBER		NOT NULL,
	"NOTE_CONTENT"	NVARCHAR2(2000)		NOT NULL,
	"NOTE_COLOR"	NVARCHAR2(20)	DEFAULT 'WHITE'	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_TYPE_NO"	NUMBER	DEFAULT 4	NOT NULL
);

COMMENT ON COLUMN "NOTE"."NOTE_NO" IS '메모장 번호(PK)';

COMMENT ON COLUMN "NOTE"."NOTE_CONTENT" IS '메모장 내용';

COMMENT ON COLUMN "NOTE"."NOTE_COLOR" IS '메모장 배경색';

COMMENT ON COLUMN "NOTE"."MEMBER_NO" IS '작성회원(FK)';

COMMENT ON COLUMN "NOTE"."BOARD_TYPE_NO" IS '게시판 종류 번호(FK)';


ALTER TABLE "NOTE" ADD CONSTRAINT "PK_NOTE" PRIMARY KEY (
	"NOTE_NO"
);


ALTER TABLE "NOTE" ADD CONSTRAINT "FK_MEMBER_TO_NOTE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
) ON DELETE CASCADE;

ALTER TABLE "NOTE" ADD CONSTRAINT "FK_BOARD_TYPE_TO_NOTE_1" FOREIGN KEY (
	"BOARD_TYPE_NO"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_TYPE_NO"
) ON DELETE CASCADE;



------------------------------------ 공지사항 "ALERT" 테이블
CREATE TABLE "ALERT" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"ALERT_CONTENT"	NVARCHAR2(2000)		NULL,
	"BOARD_TYPE_NO"	NUMBER	DEFAULT 5	NOT NULL
);

COMMENT ON COLUMN "ALERT"."MEMBER_NO" IS '회원고유번호(FPK)';

COMMENT ON COLUMN "ALERT"."ALERT_CONTENT" IS '공지사항 내용';

COMMENT ON COLUMN "ALERT"."BOARD_TYPE_NO" IS '게시판 종류 번호(FK)';


-- 제약조건
ALTER TABLE "ALERT" ADD CONSTRAINT "PK_ALERT" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "ALERT" ADD CONSTRAINT "FK_MEMBER_TO_ALERT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
) ON DELETE CASCADE;



ALTER TABLE "ALERT" ADD CONSTRAINT "FK_BOARD_TYPE_TO_ALERT_1" FOREIGN KEY (
	"BOARD_TYPE_NO"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_TYPE_NO"
) ON DELETE CASCADE;


------------------------------------ 이미지 경로 "IMG" 테이블
CREATE TABLE "IMG" (
	"IMG_NO"	NUMBER		NOT NULL,
	"IMG_PATH"	VARCHAR2(200)		NOT NULL,
	"IMG_ORIGINAL_NAME"	NVARCHAR2(50)		NOT NULL,
	"IMG_ORDER"	NUMBER		NOT NULL,
	"IMG_BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TYPE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "IMG"."IMG_NO" IS '사진번호(PK)';

COMMENT ON COLUMN "IMG"."IMG_PATH" IS '사진 경로';

COMMENT ON COLUMN "IMG"."IMG_ORIGINAL_NAME" IS '사진 원본명';

COMMENT ON COLUMN "IMG"."IMG_ORDER" IS '사진 순서';

COMMENT ON COLUMN "IMG"."IMG_BOARD_NO" IS '게시글 번호';

COMMENT ON COLUMN "IMG"."BOARD_TYPE_NO" IS '게시판 종류 번호(FK)';


-- 제약 조건
ALTER TABLE "IMG" ADD CONSTRAINT "PK_IMG" PRIMARY KEY (
	"IMG_NO"
);

ALTER TABLE "IMG" ADD CONSTRAINT "FK_BOARD_TYPE_TO_IMG_1" FOREIGN KEY (
	"BOARD_TYPE_NO"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_TYPE_NO"
) ON DELETE CASCADE;


------------------------------------ 팔로우 "FOLLOW" 테이블
CREATE TABLE "FOLLOW" (
	"FOLLOWER_ID"	NUMBER		NOT NULL,
	"FOLLOWING_ID"	NUMBER		NOT NULL,
	"FOLLOW_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "FOLLOW"."FOLLOWER_ID" IS '회원 번호(PK)';

COMMENT ON COLUMN "FOLLOW"."FOLLOWING_ID" IS '회원 번호(PFK)';

COMMENT ON COLUMN "FOLLOW"."FOLLOW_DATE" IS '팔로우한날짜';


-- 제약조건
ALTER TABLE "FOLLOW" ADD CONSTRAINT "PK_FOLLOW" PRIMARY KEY (FOLLOWER_ID, FOLLOWING_ID);

-- FOREIGN KEY 설정 (팔로워, 팔로잉 회원은 MEMBER 테이블의 MEMBER_NO를 참조)
ALTER TABLE "FOLLOW" ADD CONSTRAINT FK_FOLLOWER FOREIGN KEY (FOLLOWER_ID) REFERENCES "MEMBER" (MEMBER_NO) ON DELETE CASCADE;
ALTER TABLE "FOLLOW" ADD CONSTRAINT FK_FOLLOWING FOREIGN KEY (FOLLOWING_ID) REFERENCES "MEMBER" (MEMBER_NO) ON DELETE CASCADE;



------------------------------------ 프로필 "PROFILE_IMG" 테이블
CREATE TABLE "PROFILE_IMG" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"PROFILE_PATH"	VARCHAR2(500)		NOT NULL,
	"PROFILE_ORRIGINAL_NAME"	VARCHAR2(300)		NOT NULL,
	"PROFILE_RENAME"	VARCHAR2(100)		NOT NULL,
	"PROFILE_UPLOAD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "PROFILE_IMG"."MEMBER_NO" IS '프로필 회원(FPK)';

COMMENT ON COLUMN "PROFILE_IMG"."PROFILE_PATH" IS '프로필 경로';

COMMENT ON COLUMN "PROFILE_IMG"."PROFILE_ORRIGINAL_NAME" IS '이미지 원본명';

COMMENT ON COLUMN "PROFILE_IMG"."PROFILE_RENAME" IS '이미지 변경명';

COMMENT ON COLUMN "PROFILE_IMG"."PROFILE_UPLOAD_DATE" IS '업로드 날짜';

ALTER TABLE "PROFILE_IMG" ADD CONSTRAINT "PK_PROFILE_IMG" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "PROFILE_IMG" ADD CONSTRAINT "FK_MEMBER_TO_PROFILE_IMG_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
) ON DELETE CASCADE;

ALTER TABLE "PROFILE_IMG" DROP CONSTRAINT "FK_MEMBER_TO_PROFILE_IMG_1";



------------------------------------ 댓글 "COMMENT" 테이블
CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"COMMENT_CONTENT"	NVARCHAR2(2000)		NOT NULL,
	"COMMENT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COMMENT_DEL_FL"	CHAR(1) DEFAULT 'N' NOT	NULL,
	"TEXT_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_TYPE_NO"	NUMBER		NOT NULL,
	"PARENT_COMMENT_NO2"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '댓글번호';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글내용';

COMMENT ON COLUMN "COMMENT"."COMMENT_DATE" IS '댓글 작성일';

COMMENT ON COLUMN "COMMENT"."COMMENT_DEL_FL" IS '댓글 삭제여부(Y, N)';

COMMENT ON COLUMN "COMMENT"."TEXT_NO" IS '글 번호';

COMMENT ON COLUMN "COMMENT"."MEMBER_NO" IS '회원 번호(FK)';

COMMENT ON COLUMN "COMMENT"."BOARD_TYPE_NO" IS '게시판 종류 번호(FK)';

COMMENT ON COLUMN "COMMENT"."PARENT_COMMENT_NO2" IS '부모댓글 번호(FK)';


-- 제약 조건
ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
) ON DELETE CASCADE;

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_BOARD_TYPE_TO_COMMENT_1" FOREIGN KEY (
	"BOARD_TYPE_NO"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_TYPE_NO"
) ON DELETE CASCADE;

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_1" FOREIGN KEY (
	"PARENT_COMMENT_NO2"
)
REFERENCES "COMMENT" (
	"COMMENT_NO"
) ON DELETE SET NULL;
-- 댓글 삭제 알고리즘 고민하기









------------------------------------ 좋아요 "LIKE" 테이블
CREATE TABLE "LIKE" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TYPE_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "LIKE"."BOARD_NO" IS '글 번호(PK)';

COMMENT ON COLUMN "LIKE"."BOARD_TYPE_NO" IS '게시판 종류(FPK)';

COMMENT ON COLUMN "LIKE"."MEMBER_NO" IS '회원고유번호(FPK)';


-- 제약조건
ALTER TABLE "LIKE" ADD CONSTRAINT "PK_LIKE" PRIMARY KEY (
	"BOARD_NO",
	"BOARD_TYPE_NO",
	"MEMBER_NO"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "FK_BOARD_TYPE_TO_LIKE_1" FOREIGN KEY (
	"BOARD_TYPE_NO"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_TYPE_NO"
) ON DELETE CASCADE;

ALTER TABLE "LIKE" ADD CONSTRAINT "FK_MEMBER_TO_LIKE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
) ON DELETE CASCADE;



------------------------------------ 이메일 인증키
CREATE TABLE "AUTH_KEY" (
	"KEY_NO"	NUMBER		NOT NULL,
	"EMAIL"	NVARCHAR2(50)		NOT NULL,
	"AUTH_KEY" CHAR(6) 	NOT NULL,
	"CREATE_TIME" DATE 	DEFAULT SYSDATE NOT NULL
);



COMMENT ON COLUMN "AUTH_KEY"."KEY_NO" IS '인증키 테이블 고유번호';

COMMENT ON COLUMN "AUTH_KEY"."EMAIL" IS '인증 이메일';

COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY" IS '인증 키';

COMMENT ON COLUMN "AUTH_KEY"."CREATE_TIME" IS '인증키 생성시간';

ALTER TABLE "AUTH_KEY" ADD CONSTRAINT "PK_AUTH_KEY" PRIMARY KEY (
	"KEY_NO"
);

-------------------------------------시퀀스 생성

-- 멤버 시퀀스 생성
CREATE SEQUENCE MEM_SEQ;
-- 게시판 시퀀스 생성
CREATE SEQUENCE BOARD_SEQ;
-- 사진첩 시퀀스 생성
CREATE SEQUENCE PHOTO_SEQ;
-- 방명록 시퀀스 생성
CREATE SEQUENCE VISITOR_SEQ;
-- 메모장 시퀀스 생성
CREATE SEQUENCE NOTE_SEQ;
-- 댓글 시퀀스 생성
CREATE SEQUENCE COMMENT_SEQ;

DROP SEQUENCE ALERT_SEQ;

SELECT * FROM USER_SEQUENCES;


------------------------------------------------------------------------------- 테이블 삭제

DROP TABLE "MEMBER" CASCADE CONSTRAINTS;
DROP TABLE "BOARD" CASCADE CONSTRAINTS;
DROP TABLE "PHOTO" CASCADE CONSTRAINTS;
DROP TABLE "VISITOR" CASCADE CONSTRAINTS;
DROP TABLE "ALERT" CASCADE CONSTRAINTS;
DROP TABLE "COMMENT" CASCADE CONSTRAINTS;
DROP TABLE "BOARD_TYPE" CASCADE CONSTRAINTS;
DROP TABLE "LIKE" CASCADE CONSTRAINTS;
DROP TABLE "NOTE" CASCADE CONSTRAINTS;
DROP TABLE "IMG" CASCADE CONSTRAINTS;
DROP TABLE "PROFILE_IMG" CASCADE CONSTRAINTS;